# Generated by Django 5.2.8 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_link",
            field=models.URLField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачено"),
                    ("paid", "Оплачено"),
                    ("canceled", "Отменено"),
                ],
                default="unpaid",
                max_length=50,
                verbose_name="Статус оплаты в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии в Stripe"
            ),
        ),
    ]
