# Generated by Django 5.2.8 on 2025-12-17 09:12

from django.db import migrations, models

import materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[materials.validators.validate_youtube_url],
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
